### ISSUE TITLE
Playground should support 'vendor/otterdog-defaults/otterdog-defaults.libsonnet'

### ISSUE THREAD

**Issue by koppor** [eclipse-csi/otterdog#315]
At https://github.com/winery/.eclipsefdn/blob/eea562ab0d785552d75f237a0484016dcbff03dd/otterdog/winery.jsonnet, the first line is

    local orgs = import 'vendor/otterdog-defaults/otterdog-defaults.libsonnet';

I copy and paste the full jsonnet file into https://otterdog.eclipse.org/projects/automotive.winery/playground

I get

```
Error: RUNTIME ERROR: File not found vendor/otterdog-defaults/otterdog-defaults.libsonnet
	playground.jsonnet:1:14-75	thunk <orgs> from <$>
	playground.jsonnet:3:1-5	
	During evaluation	
```

---

I was assuming that a working file is also working the playground.

**Comment by netomi** [comment]
the playground sets up the default config by default, thats the first line here:

![image](https://github.com/user-attachments/assets/e8f3eb40-8466-4649-97b0-9f665fb225de)

**Comment by koppor** [comment]
> the playground sets up the default config by default, thats the first line here:

Sure. 

I think, I need to contact `eclipse-winery-bot` and you why they chose another import :p. (Source of contributors: https://github.com/winery/.eclipsefdn/commits/eea562ab0d785552d75f237a0484016dcbff03dd/)

---

I thought, I could play around with my config in the playground. But, maybe, this is not an aim of the playground.

**Comment by netomi** [comment]
you can play around with your config in the playground, just leave out the first line and keep the one that is preconfigured in the playground. The actual default config is present here: https://github.com/EclipseFdn/otterdog-defaults/blob/main/otterdog-defaults.libsonnet is versioned and needs to be downloaded before use. So the playground sets up everything for you. I can try to keep the name the same so that you more easily can copy in the full config, but so far that was not the goal, but rather to test out snippets quickly.

**Comment by netomi** [comment]
ok I managed to change the filenames in the playground so that you can test out your existing config unmodified:

![image](https://github.com/user-attachments/assets/c137355c-5c94-418c-81aa-b75aaa9f347d)

will deploy that soon.

**Comment by netomi** [comment]
Its now live.
